# Teleop configuration for Microsoft Xbox One controller with Wireless USB Dongle.
# Left thumb-stick up/down for velocity, left/right for twist
# A button for enable
# Left thumb-stick button for enable-turbo
#
#
# BUTTON         Value
#   LB             4
#   RB             5
#   LS             9
#   RS             10
#   A              0
#   B              1
#   X              2
#   Y              3
#   View           6
#   Menu           7
#
# AXIS           Value
# Left Horiz.      0
# Left Vert.       1
# Right Horiz.     3
# Right Vert.      4
# LT               2
# RT               5
# D-pad Horiz.     6
# D-pad Vert.      7

teleop:
  rotate_turret:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: turret/cmd_vel
    axis_mappings:
      -
        axis: 3
        target: angular.z
        scale: 1.0